// Routes a loop through every stop along real streets and saves the geometry to
// src/data/route.generated.json, so the app never calls a routing API at runtime.
//
//   npm run route                      # public OSRM demo server (fine for occasional use)
//   ORS_API_KEY=... npm run route      # OpenRouteService instead (free key at openrouteservice.org)
//   ROUTE_ORDER=colosseum,trevi,... npm run route   # custom order (defaults to marker numbers)
//
// Stops in pedestrian zones (Navona, Trevi, Spanish Steps…) snap to the nearest street.

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { stops } from '../src/data/stops.ts';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const order = process.env.ROUTE_ORDER
  ? process.env.ROUTE_ORDER.split(',').map((id) => id.trim())
  : [...stops].sort((a, b) => a.number - b.number).map((s) => s.id);
const byId = Object.fromEntries(stops.map((s) => [s.id, s]));
const unknown = order.filter((id) => !byId[id]);
if (unknown.length) throw new Error(`Unknown stop ids in ROUTE_ORDER: ${unknown.join(', ')}`);

// Close the loop back to the first stop.
const points = [...order, order[0]].map((id) => byId[id].coords);

async function osrm() {
  const coords = points.map(([lng, lat]) => `${lng},${lat}`).join(';');
  const url = `https://router.project-osrm.org/route/v1/driving/${coords}?overview=full&geometries=geojson`;
  const res = await fetch(url, { headers: { 'User-Agent': 'kirba-tours-route-builder' } });
  if (!res.ok) throw new Error(`OSRM ${res.status}: ${await res.text()}`);
  const json = await res.json();
  return { source: 'OSRM (router.project-osrm.org), driving profile', geometry: json.routes[0].geometry, meters: json.routes[0].distance };
}

async function ors(key) {
  const res = await fetch('https://api.openrouteservice.org/v2/directions/driving-car/geojson', {
    method: 'POST',
    headers: { Authorization: key, 'Content-Type': 'application/json' },
    body: JSON.stringify({ coordinates: points }),
  });
  if (!res.ok) throw new Error(`OpenRouteService ${res.status}: ${await res.text()}`);
  const json = await res.json();
  const f = json.features[0];
  return { source: 'OpenRouteService, driving-car profile', geometry: f.geometry, meters: f.properties.summary.distance };
}

const result = process.env.ORS_API_KEY ? await ors(process.env.ORS_API_KEY) : await osrm();
// Round to ~1 m to keep the file small.
result.geometry.coordinates = result.geometry.coordinates.map(([x, y]) => [+x.toFixed(5), +y.toFixed(5)]);

writeFileSync(
  join(root, 'src/data/route.generated.json'),
  JSON.stringify(
    {
      note: 'Generated by `npm run route`. Do not edit by hand.',
      generatedAt: new Date().toISOString(),
      source: result.source,
      order,
      geometry: result.geometry,
    },
    null,
    1,
  ) + '\n',
);
console.log(`✓ ${order.length}-stop loop, ${(result.meters / 1000).toFixed(1)} km, ${result.geometry.coordinates.length} points`);
